/**
 * -----------------------------------------------------------------------------
 * Project: Fossil Logic
 *
 * This file is part of the Fossil Logic project, which aims to develop
 * high-performance, cross-platform applications and libraries. The code
 * contained herein is licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain
 * a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * Author: Michael Gene Brockus (Dreamer)
 * Date: 04/05/2014
 *
 * Copyright (C) 2014-2025 Fossil Logic. All rights reserved.
 * -----------------------------------------------------------------------------
 */
#ifndef FOSSIL_IO_ERROR_H
#define FOSSIL_IO_ERROR_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    // Success and General Errors
    FOSSIL_ERROR_OK = 0,
    FOSSIL_ERROR_CNULL_POINTER,
    FOSSIL_ERROR_INVALID_ARGUMENT,
    FOSSIL_ERROR_TYPE_MISMATCH,
    FOSSIL_ERROR_INVALID_OPERATION,
    FOSSIL_ERROR_UNKNOWN,
    FOSSIL_ERROR_CUSTOM,
    FOSSIL_ERROR_INTERNAL,
    FOSSIL_ERROR_UNKNOWN_ERROR_CODE,

    // Arithmetic Errors
    FOSSIL_ERROR_OVERFLOW_INT,
    FOSSIL_ERROR_UNDERFLOW_INT,
    FOSSIL_ERROR_OVERFLOW_FLOAT,
    FOSSIL_ERROR_UNDERFLOW_FLOAT,
    FOSSIL_ERROR_DIVISION_BY_ZERO,
    FOSSIL_ERROR_INVALID_CAST,

    // Memory Errors
    FOSSIL_ERROR_OUT_OF_MEMORY,
    FOSSIL_ERROR_MEMORY_CORRUPTION,
    FOSSIL_ERROR_BUFFER_OVERFLOW,
    FOSSIL_ERROR_BUFFER_UNDERFLOW,
    FOSSIL_ERROR_BUFFER_OVERFLOW_STR,
    FOSSIL_ERROR_BUFFER_OVERFLOW_FMT,
    FOSSIL_ERROR_BUFFER_OVERFLOW_FILE,
    FOSSIL_ERROR_BUFFER_OVERFLOW_NET,
    FOSSIL_ERROR_BUFFER_OVERFLOW_CMD,
    FOSSIL_ERROR_BUFFER_OVERFLOW_ENV,
    FOSSIL_ERROR_MEMORY_LEAK,
    FOSSIL_ERROR_MEMORY_ALLOCATION_FAILURE,
    FOSSIL_ERROR_MEMORY_ALIGNMENT_ISSUE,

    // File and I/O Errors
    FOSSIL_ERROR_FILE_CORRUPTION,
    FOSSIL_ERROR_FILE_NOT_FOUND,
    FOSSIL_ERROR_DIRECTORY_NOT_FOUND,
    FOSSIL_ERROR_TOO_MANY_OPEN_FILES,
    FOSSIL_ERROR_IO,
    FOSSIL_ERROR_UNSUPPORTED_OPERATION,
    FOSSIL_ERROR_PIPE,
    FOSSIL_ERROR_SYSTEM_CALL_FAILED,
    FOSSIL_ERROR_PERMISSION_DENIED,
    FOSSIL_ERROR_READ_ONLY_FILESYSTEM,
    FOSSIL_ERROR_FILE_LOCK_FAILED,
    FOSSIL_ERROR_FILE_WRITE_FAILED,
    FOSSIL_ERROR_FILE_READ_FAILED,
    FOSSIL_ERROR_FILE_SEEK_FAILED,
    FOSSIL_ERROR_FILE_CLOSE_FAILED,
    FOSSIL_ERROR_FILE_TRUNCATE_FAILED,
    FOSSIL_ERROR_FILE_TOO_LARGE,
    FOSSIL_ERROR_DEVICE_NOT_READY,
    FOSSIL_ERROR_DEVICE_REMOVED,

    // Resource and Process Errors
    FOSSIL_ERROR_RESOURCE_UNAVAILABLE,
    FOSSIL_ERROR_BUSY,
    FOSSIL_ERROR_DEADLOCK,
    FOSSIL_ERROR_INTERRUPTED,
    FOSSIL_ERROR_LIMIT_REACHED,
    FOSSIL_ERROR_PROCESS,
    FOSSIL_ERROR_PROCESS_CREATION_FAILED,
    FOSSIL_ERROR_PROCESS_EXITED_WITH_ERROR,
    FOSSIL_ERROR_PROCESS_TIMEOUT,
    FOSSIL_ERROR_RESOURCE_DEPLETION,
    FOSSIL_ERROR_THREAD_CREATION_FAILED,
    FOSSIL_ERROR_THREAD_TERMINATION_FAILED,

    // Hardware Errors
    FOSSIL_ERROR_HARDWARE_FAILURE,
    FOSSIL_ERROR_HARD_DISK_FAILURE,
    FOSSIL_ERROR_CPU_OVERHEAT,
    FOSSIL_ERROR_MEMORY_FAILURE,
    FOSSIL_ERROR_HARDWARE_OVERLOAD,
    FOSSIL_ERROR_DEVICE_TIMEOUT,
    FOSSIL_ERROR_POWER_SUPPLY_FAILURE,
    FOSSIL_ERROR_MOTHERBOARD_FAILURE,
    FOSSIL_ERROR_CPU_FAILURE,
    FOSSIL_ERROR_RAM_FAILURE,
    FOSSIL_ERROR_SSD_FAILURE,
    FOSSIL_ERROR_HDD_FAILURE,
    FOSSIL_ERROR_FAN_FAILURE,
    FOSSIL_ERROR_GPU_FAILURE,
    FOSSIL_ERROR_BATTERY_FAILURE,
    FOSSIL_ERROR_SENSOR_FAILURE,
    FOSSIL_ERROR_USB_CONTROLLER_FAILURE,
    FOSSIL_ERROR_PCI_DEVICE_FAILURE,
    FOSSIL_ERROR_NETWORK_CARD_FAILURE,
    FOSSIL_ERROR_SOUND_CARD_FAILURE,
    FOSSIL_ERROR_DISPLAY_ADAPTER_FAILURE,
    FOSSIL_ERROR_POWER_SUPPLY_OVERVOLTAGE,
    FOSSIL_ERROR_POWER_SUPPLY_UNDERVOLTAGE,
    FOSSIL_ERROR_THERMAL_SHUTDOWN,
    FOSSIL_ERROR_FIRMWARE_CORRUPTION,
    FOSSIL_ERROR_HARDWARE_INCOMPATIBILITY,
    FOSSIL_ERROR_HARDWARE_NOT_DETECTED,
    FOSSIL_ERROR_HARDWARE_DRIVER_MISSING,
    FOSSIL_ERROR_HARDWARE_DRIVER_CORRUPTED,

    // Network Errors
    FOSSIL_ERROR_NETWORK_FAILURE,
    FOSSIL_ERROR_TIMEOUT,
    FOSSIL_ERROR_UNKNOWN_HOST,
    FOSSIL_ERROR_CONNECTION_REFUSED,
    FOSSIL_ERROR_NETWORK_UNREACHABLE,
    FOSSIL_ERROR_PROTOCOL,
    FOSSIL_ERROR_CONNECTION_RESET,
    FOSSIL_ERROR_DNS_RESOLUTION_FAILED,
    FOSSIL_ERROR_NETWORK_CONGESTION,
    FOSSIL_ERROR_BANDWIDTH_EXCEEDED,
    FOSSIL_ERROR_FIREWALL_BLOCKED,
    FOSSIL_ERROR_SSL_HANDSHAKE_FAILED,
    FOSSIL_ERROR_CERTIFICATE_EXPIRED,
    FOSSIL_ERROR_CERTIFICATE_REVOKED,

    // Security Errors
    FOSSIL_ERROR_SQL_INJECTION,
    FOSSIL_ERROR_XSS_ATTACK,
    FOSSIL_ERROR_CSRF_ATTACK,
    FOSSIL_ERROR_FORMAT_STRING_ATTACK,
    FOSSIL_ERROR_CRYPTOGRAPHIC_WEAKNESS,
    FOSSIL_ERROR_INSECURE_RANDOMNESS,
    FOSSIL_ERROR_INSECURE_CONFIGURATION,
    FOSSIL_ERROR_INSECURE_DESERIALIZATION,
    FOSSIL_ERROR_INSECURE_FILE_HANDLING,
    FOSSIL_ERROR_INSECURE_TEMPORARY_FILES,
    FOSSIL_ERROR_INSECURE_COMMUNICATION,
    FOSSIL_ERROR_INSECURE_AUTHENTICATION,
    FOSSIL_ERROR_INSECURE_ACCESS_CONTROL,
    FOSSIL_ERROR_SESSION_HIJACKING,
    FOSSIL_ERROR_DATA_TAMPERING,
    FOSSIL_ERROR_MAN_IN_THE_MIDDLE_ATTACK,
    FOSSIL_ERROR_PRIVILEGE_ESCALATION,

    // User-Related and External Errors
    FOSSIL_ERROR_USER_ABORT,
    FOSSIL_ERROR_SIGNAL,
    FOSSIL_ERROR_USER_INPUT_TOO_LARGE,
    FOSSIL_ERROR_USER_INPUT_INVALID_FORMAT,
    FOSSIL_ERROR_USER_PERMISSION_REJECTED,

    // Database Errors
    FOSSIL_ERROR_DATABASE_CONNECTION_FAILED,
    FOSSIL_ERROR_DATABASE_QUERY_FAILED,
    FOSSIL_ERROR_DATABASE_TIMEOUT,
    FOSSIL_ERROR_DATABASE_CORRUPTION,
    FOSSIL_ERROR_DATABASE_DEADLOCK,
    FOSSIL_ERROR_DATABASE_LOCK_FAILED,

    // Serialization and Deserialization Errors
    FOSSIL_ERROR_SERIALIZATION_FAILED,
    FOSSIL_ERROR_DESERIALIZATION_FAILED,
    FOSSIL_ERROR_INVALID_SERIALIZATION_FORMAT,
    FOSSIL_ERROR_DATA_CORRUPTION,

    // Miscellaneous Errors
    FOSSIL_ERROR_INDEX_OUT_OF_BOUNDS,
    FOSSIL_ERROR_FORMAT,
    FOSSIL_ERROR_INCOMPATIBLE_VERSION,
    FOSSIL_ERROR_JSON_PARSING_FAILED,
    FOSSIL_ERROR_XML_PARSING_FAILED,
    FOSSIL_ERROR_YAML_PARSING_FAILED,
    FOSSIL_ERROR_INVALID_CHECKSUM,
    FOSSIL_ERROR_TIMER_EXPIRED,

    // Truthful Intelligence Errors (TI)
    FOSSIL_ERROR_TI_MODEL_NOT_FOUND,              // TI: FOSSIL_ERROR_AI_MODEL_NOT_FOUND
    FOSSIL_ERROR_TI_INFERENCE_FAILED,             // TI: FOSSIL_ERROR_AI_INFERENCE_FAILED
    FOSSIL_ERROR_TI_TRAINING_FAILED,              // TI: FOSSIL_ERROR_AI_TRAINING_FAILED
    FOSSIL_ERROR_TI_INVALID_INPUT,                // TI: FOSSIL_ERROR_AI_INVALID_INPUT
    FOSSIL_ERROR_TI_UNSUPPORTED_OPERATION,        // TI: FOSSIL_ERROR_AI_UNSUPPORTED_OPERATION
    FOSSIL_ERROR_TI_TIMEOUT,                      // TI: FOSSIL_ERROR_AI_TIMEOUT
    FOSSIL_ERROR_TI_MODEL_CORRUPTION,             // TI: FOSSIL_ERROR_AI_MODEL_CORRUPTION
    FOSSIL_ERROR_TI_INSUFFICIENT_RESOURCES,       // TI: FOSSIL_ERROR_AI_INSUFFICIENT_RESOURCES
    FOSSIL_ERROR_TI_INVALID_CONFIGURATION,        // TI: FOSSIL_ERROR_AI_INVALID_CONFIGURATION
    FOSSIL_ERROR_TI_DATASET_NOT_FOUND,            // TI: FOSSIL_ERROR_AI_DATASET_NOT_FOUND
    FOSSIL_ERROR_TI_DATASET_CORRUPTION,           // TI: FOSSIL_ERROR_AI_DATASET_CORRUPTION
    FOSSIL_ERROR_TI_EVALUATION_FAILED,            // TI: FOSSIL_ERROR_AI_EVALUATION_FAILED
    FOSSIL_ERROR_TI_UNSUPPORTED_MODEL_TYPE,       // TI: FOSSIL_ERROR_AI_UNSUPPORTED_MODEL_TYPE
    FOSSIL_ERROR_TI_INCOMPATIBLE_MODEL_VERSION,   // TI: FOSSIL_ERROR_AI_INCOMPATIBLE_MODEL_VERSION
    FOSSIL_ERROR_TI_INVALID_PARAMETER,            // TI: FOSSIL_ERROR_AI_INVALID_PARAMETER
    FOSSIL_ERROR_TI_UNEXPECTED_OUTPUT,            // TI: FOSSIL_ERROR_AI_UNEXPECTED_OUTPUT

    //
} fossil_status_t;

/**
 * This function is used to report an error message with a formatted string.
 *
 * @param format The format string for the error message.
 * @param ... The additional arguments to be formatted.
 */
void fossil_io_error(const char *format, ...);

/**
 * This function is used to get a human-readable description of an error code.
 *
 * @param error_code The error code for which the description is needed.
 * @return The human-readable description of the error code.
 */
const char *fossil_io_what(fossil_status_t error_code);

#ifdef __cplusplus
}

#include <exception>

/**
 * This namespace provides a set of functions for handling input and output operations.
 */
namespace fossil {
    /**
     * This namespace provides a set of functions for handling input and output operations.
     */
    namespace io {
        /**
         * Enum class for error codes.
         */
        enum class ErrorCode {
            // Success and General Errors
            OK = FOSSIL_ERROR_OK,
            NULL_POINTER = FOSSIL_ERROR_CNULL_POINTER,
            INVALID_ARGUMENT = FOSSIL_ERROR_INVALID_ARGUMENT,
            TYPE_MISMATCH = FOSSIL_ERROR_TYPE_MISMATCH,
            INVALID_OPERATION = FOSSIL_ERROR_INVALID_OPERATION,
            UNKNOWN = FOSSIL_ERROR_UNKNOWN,
            CUSTOM = FOSSIL_ERROR_CUSTOM,
            INTERNAL = FOSSIL_ERROR_INTERNAL,
            UNKNOWN_ERROR_CODE = FOSSIL_ERROR_UNKNOWN_ERROR_CODE,

            // Arithmetic Errors
            OVERFLOW_INT = FOSSIL_ERROR_OVERFLOW_INT,
            UNDERFLOW_INT = FOSSIL_ERROR_UNDERFLOW_INT,
            OVERFLOW_FLOAT = FOSSIL_ERROR_OVERFLOW_FLOAT,
            UNDERFLOW_FLOAT = FOSSIL_ERROR_UNDERFLOW_FLOAT,
            DIVISION_BY_ZERO = FOSSIL_ERROR_DIVISION_BY_ZERO,
            INVALID_CAST = FOSSIL_ERROR_INVALID_CAST,

            // Memory Errors
            OUT_OF_MEMORY = FOSSIL_ERROR_OUT_OF_MEMORY,
            MEMORY_CORRUPTION = FOSSIL_ERROR_MEMORY_CORRUPTION,
            BUFFER_OVERFLOW = FOSSIL_ERROR_BUFFER_OVERFLOW,
            BUFFER_UNDERFLOW = FOSSIL_ERROR_BUFFER_UNDERFLOW,
            BUFFER_OVERFLOW_STR = FOSSIL_ERROR_BUFFER_OVERFLOW_STR,
            BUFFER_OVERFLOW_FMT = FOSSIL_ERROR_BUFFER_OVERFLOW_FMT,
            BUFFER_OVERFLOW_FILE = FOSSIL_ERROR_BUFFER_OVERFLOW_FILE,
            BUFFER_OVERFLOW_NET = FOSSIL_ERROR_BUFFER_OVERFLOW_NET,
            BUFFER_OVERFLOW_CMD = FOSSIL_ERROR_BUFFER_OVERFLOW_CMD,
            BUFFER_OVERFLOW_ENV = FOSSIL_ERROR_BUFFER_OVERFLOW_ENV,
            MEMORY_LEAK = FOSSIL_ERROR_MEMORY_LEAK,
            MEMORY_ALLOCATION_FAILURE = FOSSIL_ERROR_MEMORY_ALLOCATION_FAILURE,
            MEMORY_ALIGNMENT_ISSUE = FOSSIL_ERROR_MEMORY_ALIGNMENT_ISSUE,

            // File and I/O Errors
            FILE_CORRUPTION = FOSSIL_ERROR_FILE_CORRUPTION,
            FILE_NOT_FOUND = FOSSIL_ERROR_FILE_NOT_FOUND,
            DIRECTORY_NOT_FOUND = FOSSIL_ERROR_DIRECTORY_NOT_FOUND,
            TOO_MANY_OPEN_FILES = FOSSIL_ERROR_TOO_MANY_OPEN_FILES,
            IO = FOSSIL_ERROR_IO,
            UNSUPPORTED_OPERATION = FOSSIL_ERROR_UNSUPPORTED_OPERATION,
            PIPE = FOSSIL_ERROR_PIPE,
            SYSTEM_CALL_FAILED = FOSSIL_ERROR_SYSTEM_CALL_FAILED,
            PERMISSION_DENIED = FOSSIL_ERROR_PERMISSION_DENIED,
            READ_ONLY_FILESYSTEM = FOSSIL_ERROR_READ_ONLY_FILESYSTEM,
            FILE_LOCK_FAILED = FOSSIL_ERROR_FILE_LOCK_FAILED,
            FILE_WRITE_FAILED = FOSSIL_ERROR_FILE_WRITE_FAILED,
            FILE_READ_FAILED = FOSSIL_ERROR_FILE_READ_FAILED,
            FILE_SEEK_FAILED = FOSSIL_ERROR_FILE_SEEK_FAILED,
            FILE_CLOSE_FAILED = FOSSIL_ERROR_FILE_CLOSE_FAILED,
            FILE_TRUNCATE_FAILED = FOSSIL_ERROR_FILE_TRUNCATE_FAILED,
            FILE_TOO_LARGE = FOSSIL_ERROR_FILE_TOO_LARGE,
            DEVICE_NOT_READY = FOSSIL_ERROR_DEVICE_NOT_READY,
            DEVICE_REMOVED = FOSSIL_ERROR_DEVICE_REMOVED,

            // Resource and Process Errors
            RESOURCE_UNAVAILABLE = FOSSIL_ERROR_RESOURCE_UNAVAILABLE,
            BUSY = FOSSIL_ERROR_BUSY,
            DEADLOCK = FOSSIL_ERROR_DEADLOCK,
            INTERRUPTED = FOSSIL_ERROR_INTERRUPTED,
            LIMIT_REACHED = FOSSIL_ERROR_LIMIT_REACHED,
            PROCESS = FOSSIL_ERROR_PROCESS,
            PROCESS_CREATION_FAILED = FOSSIL_ERROR_PROCESS_CREATION_FAILED,
            PROCESS_EXITED_WITH_ERROR = FOSSIL_ERROR_PROCESS_EXITED_WITH_ERROR,
            PROCESS_TIMEOUT = FOSSIL_ERROR_PROCESS_TIMEOUT,
            RESOURCE_DEPLETION = FOSSIL_ERROR_RESOURCE_DEPLETION,
            THREAD_CREATION_FAILED = FOSSIL_ERROR_THREAD_CREATION_FAILED,
            THREAD_TERMINATION_FAILED = FOSSIL_ERROR_THREAD_TERMINATION_FAILED,

            // Hardware Errors
            HARDWARE_FAILURE = FOSSIL_ERROR_HARDWARE_FAILURE,
            HARD_DISK_FAILURE = FOSSIL_ERROR_HARD_DISK_FAILURE,
            GPU_FAILURE = FOSSIL_ERROR_GPU_FAILURE,
            CPU_OVERHEAT = FOSSIL_ERROR_CPU_OVERHEAT,
            MEMORY_FAILURE = FOSSIL_ERROR_MEMORY_FAILURE,
            HARDWARE_OVERLOAD = FOSSIL_ERROR_HARDWARE_OVERLOAD,
            DEVICE_TIMEOUT = FOSSIL_ERROR_DEVICE_TIMEOUT,
            POWER_SUPPLY_FAILURE = FOSSIL_ERROR_POWER_SUPPLY_FAILURE,

            // Network Errors
            NETWORK_FAILURE = FOSSIL_ERROR_NETWORK_FAILURE,
            TIMEOUT = FOSSIL_ERROR_TIMEOUT,
            UNKNOWN_HOST = FOSSIL_ERROR_UNKNOWN_HOST,
            CONNECTION_REFUSED = FOSSIL_ERROR_CONNECTION_REFUSED,
            NETWORK_UNREACHABLE = FOSSIL_ERROR_NETWORK_UNREACHABLE,
            PROTOCOL = FOSSIL_ERROR_PROTOCOL,
            CONNECTION_RESET = FOSSIL_ERROR_CONNECTION_RESET,
            DNS_RESOLUTION_FAILED = FOSSIL_ERROR_DNS_RESOLUTION_FAILED,
            NETWORK_CONGESTION = FOSSIL_ERROR_NETWORK_CONGESTION,
            BANDWIDTH_EXCEEDED = FOSSIL_ERROR_BANDWIDTH_EXCEEDED,
            FIREWALL_BLOCKED = FOSSIL_ERROR_FIREWALL_BLOCKED,
            SSL_HANDSHAKE_FAILED = FOSSIL_ERROR_SSL_HANDSHAKE_FAILED,
            CERTIFICATE_EXPIRED = FOSSIL_ERROR_CERTIFICATE_EXPIRED,
            CERTIFICATE_REVOKED = FOSSIL_ERROR_CERTIFICATE_REVOKED,

            // Security Errors
            SQL_INJECTION = FOSSIL_ERROR_SQL_INJECTION,
            XSS_ATTACK = FOSSIL_ERROR_XSS_ATTACK,
            CSRF_ATTACK = FOSSIL_ERROR_CSRF_ATTACK,
            FORMAT_STRING_ATTACK = FOSSIL_ERROR_FORMAT_STRING_ATTACK,
            CRYPTOGRAPHIC_WEAKNESS = FOSSIL_ERROR_CRYPTOGRAPHIC_WEAKNESS,
            INSECURE_RANDOMNESS = FOSSIL_ERROR_INSECURE_RANDOMNESS,
            INSECURE_CONFIGURATION = FOSSIL_ERROR_INSECURE_CONFIGURATION,
            INSECURE_DESERIALIZATION = FOSSIL_ERROR_INSECURE_DESERIALIZATION,
            INSECURE_FILE_HANDLING = FOSSIL_ERROR_INSECURE_FILE_HANDLING,
            INSECURE_TEMPORARY_FILES = FOSSIL_ERROR_INSECURE_TEMPORARY_FILES,
            INSECURE_COMMUNICATION = FOSSIL_ERROR_INSECURE_COMMUNICATION,
            INSECURE_AUTHENTICATION = FOSSIL_ERROR_INSECURE_AUTHENTICATION,
            INSECURE_ACCESS_CONTROL = FOSSIL_ERROR_INSECURE_ACCESS_CONTROL,
            SESSION_HIJACKING = FOSSIL_ERROR_SESSION_HIJACKING,
            DATA_TAMPERING = FOSSIL_ERROR_DATA_TAMPERING,
            MAN_IN_THE_MIDDLE_ATTACK = FOSSIL_ERROR_MAN_IN_THE_MIDDLE_ATTACK,
            PRIVILEGE_ESCALATION = FOSSIL_ERROR_PRIVILEGE_ESCALATION,

            // User-Related and External Errors
            USER_ABORT = FOSSIL_ERROR_USER_ABORT,
            SIGNAL = FOSSIL_ERROR_SIGNAL,
            USER_INPUT_TOO_LARGE = FOSSIL_ERROR_USER_INPUT_TOO_LARGE,
            USER_INPUT_INVALID_FORMAT = FOSSIL_ERROR_USER_INPUT_INVALID_FORMAT,
            USER_PERMISSION_REJECTED = FOSSIL_ERROR_USER_PERMISSION_REJECTED,

            // Database Errors
            DATABASE_CONNECTION_FAILED = FOSSIL_ERROR_DATABASE_CONNECTION_FAILED,
            DATABASE_QUERY_FAILED = FOSSIL_ERROR_DATABASE_QUERY_FAILED,
            DATABASE_TIMEOUT = FOSSIL_ERROR_DATABASE_TIMEOUT,
            DATABASE_CORRUPTION = FOSSIL_ERROR_DATABASE_CORRUPTION,
            DATABASE_DEADLOCK = FOSSIL_ERROR_DATABASE_DEADLOCK,
            DATABASE_LOCK_FAILED = FOSSIL_ERROR_DATABASE_LOCK_FAILED,

            // Serialization and Deserialization Errors
            SERIALIZATION_FAILED = FOSSIL_ERROR_SERIALIZATION_FAILED,
            DESERIALIZATION_FAILED = FOSSIL_ERROR_DESERIALIZATION_FAILED,
            INVALID_SERIALIZATION_FORMAT = FOSSIL_ERROR_INVALID_SERIALIZATION_FORMAT,
            DATA_CORRUPTION = FOSSIL_ERROR_DATA_CORRUPTION,

            // Miscellaneous Errors
            INDEX_OUT_OF_BOUNDS = FOSSIL_ERROR_INDEX_OUT_OF_BOUNDS,
            FORMAT = FOSSIL_ERROR_FORMAT,
            INCOMPATIBLE_VERSION = FOSSIL_ERROR_INCOMPATIBLE_VERSION,
            JSON_PARSING_FAILED = FOSSIL_ERROR_JSON_PARSING_FAILED,
            XML_PARSING_FAILED = FOSSIL_ERROR_XML_PARSING_FAILED,
            YAML_PARSING_FAILED = FOSSIL_ERROR_YAML_PARSING_FAILED,
            INVALID_CHECKSUM = FOSSIL_ERROR_INVALID_CHECKSUM,
            TIMER_EXPIRED = FOSSIL_ERROR_TIMER_EXPIRED
        };

        /**
         * Exception class for handling errors.
         */
        class Error : public std::exception {
        public:
            explicit Error(ErrorCode code) : code_(code) {}

            const char* what() const noexcept override {
                return fossil_io_what(static_cast<fossil_status_t>(code_));
            }

            ErrorCode code() const noexcept {
                return code_;
            }

        private:
            ErrorCode code_;
        };
    }
}

#endif

#endif /* FOSSIL_IO_FRAMEWORK_H */
